# Simplified Chinese (China) language file
# Load this shell will replace en_US lang

# customize
LANG_CUST_INST_VERSION="版本"
LANG_CUST_INST_EXT_FILES="正在解压模块文件"
LANG_CUST_INST_EXT_LIB_X86="正在解压 x86 运行库"
LANG_CUST_INST_EXT_LIB_X64="正在解压 x86_64 运行库"
LANG_CUST_INST_EXT_LIB_ARM="正在解压 arm 运行库"
LANG_CUST_INST_EXT_LIB_ARM64="正在解压 arm64 运行库"
LANG_CUST_INST_STUB="正在预装管理器"
LANG_CUST_INST_CONF_CREATE="正在创建配置目录"
LANG_CUST_INST_CONF_OLD="使用旧目录"
LANG_CUST_DISABLE_EDXP="**警告**: 由于不兼容，此次安装会自动禁用EdXposed"
LANG_CUST_INST_CONF_NEW="使用新目录"
LANG_CUST_INST_COPY_LIB="正在复制框架运行库"
LANG_CUST_INST_REM_OLDCONF="正在移除老旧配置"
LANG_CUST_INST_COPT_EXTRA="正在复制文件"
LANG_CUST_INST_DONE="欢迎使用"

LANG_CUST_ERR_VERIFY_FAIL="无法解压校验工具!"
LANG_CUST_ERR_STUB="管理器预装失败! 请手动安装 LSPosed Manager"
LANG_CUST_ERR_PERM="无法设置权限"
LANG_CUST_ERR_CONF_CREATE="无法创建配置路径"
LANG_CUST_ERR_CONF_STORE="无法写入配置路径"
LANG_CUST_ERR_CONF_FIRST="无法创建首次安装标识"
LANG_CUST_ERR_CONF_UNINST="无法写入卸载脚本"
LANG_CUST_ERR_EXTRA_CREATE="无法创建"

# verify
LANG_VERIFY_SUCCESS="已验证"

LANG_VERIFY_ERR_MISMATCH="校验失败"
LANG_VERIFY_ERR_NOT_EXIST="不存在"
LANG_VERIFY_ERR_NOTICE="模块可能已被损坏，请从官方重新下载"

# util_functions
LANG_UTIL_PLATFORM="设备平台"

LANG_UTIL_ERR_RIRU_NOT_FOUND_1="未安装"
LANG_UTIL_ERR_RIRU_NOT_FOUND_2="请先从 Magisk Manager 中安装 Riru"
LANG_UTIL_ERR_RIRU_LOW_1="或更高版本需要被安装"
LANG_UTIL_ERR_RIRU_LOW_2="请先从 Magisk Manager 中升级 Riru"
LANG_UTIL_ERR_REQUIRE_YAHFA_1="侦测到 x86 或 x86_64 架构"
LANG_UTIL_ERR_REQUIRE_YAHFA_2="仅 YAHFA 支持 x86 或 x86_64 架构的设备"
LANG_UTIL_ERR_REQUIRE_YAHFA_3="可从 'Magisk Manager' 或 'LSPosed Manager' 中下载"
LANG_UTIL_ERR_ANDROID_UNSUPPORT_1="不支持的 Android 版本"
LANG_UTIL_ERR_ANDROID_UNSUPPORT_2="(Oreo 以下版本)"
LANG_UTIL_ERR_ANDROID_UNSUPPORT_3="从我们的 GitHub Wiki 中了解更多"
LANG_UTIL_ERR_PLATFORM_UNSUPPORT="不支持的设备平台"
LANG_UTIL_ERR_VARIANT_SELECTION="选择变种时出现错误"
LANG_UTIL_ERR_VARIANT_UNSUPPORT="不支持的变种"
LANG_UTIL_ERR_DUPINST_1="不允许重复安装"
LANG_UTIL_ERR_DUPINST_2="删除"
LANG_UTIL_ERR_DUPINST_3="并重启以继续安装"
