blank_issues_enabled: false
contact_links:
  - name: Ask a question/提问
    url: https://github.com/LSPosed/LSPosed/discussions/new?category=Q-A
    about: Please ask and answer questions here./如果有任何疑问请在这里提问
  - name: Official Telegram Channel/官方 Telegram 频道
    url: https://t.me/LSPosed
    about: Subscribe for notifications and releases/可以订阅通知和发行版
